# Generated by Django 6.0.3 on 2026-05-07 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_studentgroup'),
        ('users', '0002_registrationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='courses.studentgroup', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='user',
            name='tariff',
            field=models.CharField(choices=[('free', 'Бесплатный'), ('basic', 'Базовый'), ('standard', 'Стандартный'), ('premium', 'Премиум')], default='free', max_length=20, verbose_name='Тариф'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Студент'), ('teacher', 'Преподаватель'), ('manager', 'Менеджер'), ('admin', 'Администратор')], default='student', max_length=20, verbose_name='Роль'),
        ),
    ]
