# Generated by Django 6.0.3 on 2026-05-15 10:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_studentgroup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='assigned_sections', to=settings.AUTH_USER_MODEL, verbose_name='Прикреплённые преподаватели'),
        ),
    ]
